# Generated by Django 5.1.6 on 2025-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('duracao', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('diretor', models.CharField(max_length=100)),
                ('atores', models.CharField(max_length=100)),
            ],
        ),
    ]
